# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
working_docker: &working_docker
  docker:
    - image: circleci/node:10-browsers

version: 2.1
jobs:
  Install_Depencies:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    <<: [*working_docker]
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Execute Unit Test Coverage
          command: yarn test --coverage
      - run:
          name: Building Production build
          command: yarn build
          
workflows:
 version: 2.1
 Main_Workflow:
   jobs:
     - buildProject